"use strict";
export const ADD_PERSON = 'ADD_PERSON';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const CHAGNE_PAGE = 'CHANGE_PAGE';
export const BOOKMARK_DATA = 'BOOKMARK_DATA';
export const SELECTED_BOOKMARK = 'SELECTED_BOOKMARK';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CURRENT_CATEGORY = 'CURRENT_CATEGORY';
export const CLEAR_BOOKMARKS = 'CLEAR_BOOKMARKS';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const ADD_CATEGORY = 'ADD_CATEGORY';
